# 默认启动端口
server:
  port: 8090

spring:
  # 解决Swagger与SpringBoot版本不匹配的问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 572019

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration: #sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/recarchoi/mapper/xml/*.xml